CREATE SEQUENCE test_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE TEST (
	id NUMBER DEFAULT test_id_seq.nextval PRIMARY KEY,
	test VARCHAR2(16) NOT NULL,
	dato VARCHAR2(16) NOT NULL
)
TABLESPACE USERS;